Math.test.ts
great-lakes/botbuilder-wolf pull request #178
Opened 2019-03-07 01:43 UTC by gcrev93

Unit test for the math helper function.

Testing the randomElement function using SlotId Type.

2019-03-07 14:48 UTC, KSLHacks commented
@gcrev93 Changing base from `master` -> `development`

2019-03-07 15:09 UTC, KSLHacks commented
Wondering how we can test and actually prove the function is random? This is not used throughout the actual Wolf stages so this is not as critical.. but currently it's not proved it is indeed random. Is there a way we can provide a seed?

2019-03-07 16:03 UTC, howlowck requested changes

2019-03-07 16:03 UTC, howlowck commented on src/tests/unit/helpers/math.test.ts
> +interface MockUserState {
Remove `MockUserState`

2019-03-11 22:56 UTC, gcrev93 commented on src/tests/unit/helpers/math.test.ts
> +interface MockUserState {
removed

2019-03-11 22:57 UTC, gcrev93 commented
Just to close this PR, I removed MockState. Can we add the additional random testing as another task before closing this out? @wolf-packs/wolf-developers

2019-03-19 21:35 UTC, dnastrain approved these changes
:shipit:

2019-03-19 22:31 UTC, howlowck approved these changes

2019-03-20 03:03 UTC, merged